/*
 * Synchronization Backend
 *
 * # API to communicate data changes with  This is the REST API of the P7M services, that can be used to get notified when data in the system changes, or to send notifications that data has changed.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperTrack {
    #[serde(rename = "data")]
    pub data: Vec<models::ListWrapperTrackDataInner>,
}

impl ListWrapperTrack {
    pub fn new(data: Vec<models::ListWrapperTrackDataInner>) -> ListWrapperTrack {
        ListWrapperTrack {
            data,
        }
    }
}

